from film.views.comment import *
from film.views.actor import *
from film.views.author import *
from film.views.category import *
from film.views.country import *
from film.views.film import *
from film.views.genre import *
from film.views.bookmark import *
from film.views.wishlist import *