# Generated by Django 4.2.18 on 2025-02-04 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by_users', to='film.film'),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filmqualityvideo',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film'),
        ),
        migrations.AddField(
            model_name='filmimage',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film'),
        ),
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(related_name='films', to='film.actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='author',
            field=models.ManyToManyField(related_name='films', to='film.author'),
        ),
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.ManyToManyField(related_name='films', to='film.country'),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='films', to='film.genre'),
        ),
        migrations.AddField(
            model_name='comment',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='film.film'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='film.film'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
